version: "3.3"

services:
  # web:
  #  build: ./flask
  #  container_name: flaskapp
  #  restart: on-failure
  #  volumes:
  #    - ./flask/:/home/app
  #    - ./database:/home/database
  #    - /etc/localtime:/etc/localtime:ro
  #  networks:
  #    darkn:
  #      ipv4_address: 172.19.0.3
  #  ports:
  #    - 5010:5010
 
        
  zigbee:
   build: ./zigbee
   container_name: zigbee-python
   volumes:
     - ./zigbee:/home/app
     - ./database:/home/database
     - /run/udev:/run/udev:ro
     - /etc/localtime:/etc/localtime:ro
   devices:
     - /dev/ttyUSB0:/dev/ttyUSB0
   group_add:
      - dialout
   user: 1000:1000
   networks:
     darkn:
       ipv4_address: 172.19.0.4


  # nginx:
  #   build: ./nginx
  #   container_name: nginx
  #   ports:
  #     - 443:443
  #     - 80:82
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
  #      - ./nginx/data:/data
  #      - ./nginx/letsencrypt/ssl/fullchain.pem:/etc/nginx/ssl/fullchain.pem
  #      - ./nginx/letsencrypt/ssl/privkey.pem:/etc/nginx/ssl/privkey.pem
  #   networks:
  #     darkn:
  #       ipv4_address: 172.19.0.5
    

  # db:
  #   image: mariadb
  #   container_name: mariadb
  #   environment:
  #     MYSQL_ROOT_PASSWORD: 'Caleidoscopio96*'
  #   volumes:
  #     - ./mariadb/data:/var/lib/mysql
  #     - ./mariadb/codigo:/var/lib
  #   ports:
  #     - 3306:3306
  #   networks:
  #     darkn:
  #       ipv4_address: 172.19.0.6

  # phpmyadmin:
  #  image: phpmyadmin
  #  container_name: phpmyadmin
  #  ports:
  #    - 8080:80
  #  environment:
  #    - PMA_ARBITRARY=1
  #  networks:
  #    darkn:
  #      ipv4_address: 172.19.0.7

networks:
  darkn:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.19.0.0/16 
