version: "3"


services:
 mosquitto:
   image: eclipse-mosquitto
   container_name: mosquitto
   networks: 
    darkn:
      ipv4_address: 172.19.0.2
   volumes:
     - ./config:/mosquitto/config
     - ./data:/mosquitto/data
     - ./log:/mosquitto/log
   ports:
     - 1883:1883
     - 9001:9001
 
 zigbee2mqtt:
   container_name: zigbee2mqtt
   image: koenkk/zigbee2mqtt
   restart: unless-stopped
   volumes:
     - ./dockerzigbee/data:/app/data
     - /run/udev:/run/udev:ro
   ports:   
     - 1881:8080
   devices:
     - /dev/serial/by-id/usb-FTDI_FT232R_USB_UART_A50285BI-if00-port0:/dev/ttyUSB0
   networks:
     darkn:
       ipv4_address: 172.19.0.4

 web:
   build: .
   container_name: flaskaplic
   networks:
     darkn:
       ipv4_address: 172.19.0.3
   volumes: 
     - .:/usr/home/app
   ports:
     - 5000:5000

networks:
  darkn:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.19.0.0/16 
