version: "3"


services:
 mosquitto-python:
   build: ./mosquitto
   container_name: mosquitto-python
   networks: 
    darkn:
      ipv4_address: 172.19.0.10
   volumes:
     - ./mosquitto:/home
     - ../database:/home/database
     -  /etc/localtime:/etc/localtime:ro

 
 mosquitto:
   image: eclipse-mosquitto
   container_name: mosquitto-broker
   networks:
    darkn:
      ipv4_address: 172.19.0.2
   volumes:
     - ./config:/mosquitto/config
     - ./data:/mosquitto/data
     - ./log:/mosquitto/log
   ports:
     - 1883:1883
     - 9001:9001

networks:
  darkn:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.19.0.0/16 
